local theme = {}

function theme.load(config)
  local base00 = config.palette.base00
  local base01 = config.palette.base01
  local base02 = config.palette.base02
  local base03 = config.palette.base03
  local base04 = config.palette.base04
  local base05 = config.palette.base05
  local base06 = config.palette.base06
  local base07 = config.palette.base07
  local base08 = config.palette.base08
  local base09 = config.palette.base09
  local base0A = config.palette.base0A
  local base0B = config.palette.base0B
  local base0C = config.palette.base0C
  local base0D = config.palette.base0D
  local base0E = config.palette.base0E
  local base0F = config.palette.base0F

  local maybe = {
    background = config.transparent and "NONE" or base00,
    float_background = config.transparent_float and "NONE" or base01,
    nc_background = config.dim_nc_background and base01 or base00,
    bold = config.bold,
    italic = config.italic,
  }

  local highlights = {
    -- Vim
    ["ColorColumn"] = { bg = base02 },
    ["Conceal"] = { bg = "NONE" },
    ["CurSearch"] = { link = "IncSearch" },
    ["Cursor"] = { fg = base0F, bg = base03 },
    ["CursorColumn"] = { bg = base01 },
    ["CursorLine"] = { bg = base01 },
    ["CursorLineNr"] = { fg = base0B },
    ["DarkenedPanel"] = { bg = maybe.float_background },
    ["DarkenedStatusline"] = { bg = maybe.float_background },
    ["DiffAdd"] = { bg = base0B, blend = 20 },
    ["DiffChange"] = { bg = base02 },
    ["DiffDelete"] = { bg = base08, blend = 20 },
    ["DiffText"] = { bg = base0A, blend = 20 },
    ["diffAdded"] = { link = "DiffAdd" },
    ["diffChanged"] = { link = "DiffChange" },
    ["diffRemoved"] = { link = "DiffDelete" },
    ["Directory"] = { fg = base0C, bg = "NONE" },
    ["EndOfBuffer"] = { link = "NonText" },
    ["ErrorMsg"] = { fg = base08, bold = true },
    ["FloatBorder"] = { fg = base0B, bg = maybe.float_background },
    ["FloatTitle"] = { fg = base03 },
    ["FoldColumn"] = { fg = base03 },
    ["Folded"] = { fg = base0B, bg = maybe.float_background },
    ["IncSearch"] = { fg = base00, bg = base0A },
    ["LineNr"] = { fg = base03 },
    ["MatchParen"] = { fg = base0B, bg = base02 },
    ["ModeMsg"] = { fg = base04 },
    ["MoreMsg"] = { fg = base0B },
    ["NonText"] = { fg = base02 },
    ["Normal"] = { fg = base05, bg = maybe.background },
    ["NormalFloat"] = { fg = base0B, bg = maybe.float_background },
    ["NormalNC"] = { fg = base05, bg = maybe.nc_background },
    ["NvimInternalError"] = { fg = "#ffffff", bg = base08 },
    ["Pmenu"] = { fg = base04, bg = maybe.float_background },
    ["PmenuSbar"] = { bg = base01 },
    ["PmenuSel"] = { fg = base0B, bg = base02 },
    ["PmenuThumb"] = { bg = base0B },
    ["Question"] = { fg = base0A },
    ["QuickFixLine"] = { link = "Search" },
    ["RedrawDebugNormal"] = { fg = "#ffffff", bg = base0A },
    ["RedrawDebugClear"] = { fg = "#ffffff", bg = base0A },
    ["RedrawDebugComposed"] = { fg = "#ffffff", bg = base0C },
    ["RedrawDebugRecompose"] = { fg = "#ffffff", bg = base08 },
    ["Search"] = { fg = base00, bg = base0B },
    ["SpecialKey"] = { fg = base0C },
    ["SpellBad"] = { sp = base04, [config.line] = true },
    ["SpellCap"] = { sp = base04, [config.line] = true },
    ["SpellLocal"] = { sp = base04, [config.line] = true },
    ["SpellRare"] = { sp = base04, [config.line] = true },
    ["SignColumn"] = { fg = base0B, bg = maybe.background },
    ["StatusLine"] = { fg = base04, bg = base01 },
    ["StatusLineNC"] = { fg = base03, bg = base01 },
    ["StatusLineTerm"] = { link = "StatusLine" },
    ["StatusLineTermNC"] = { link = "StatusLineNC" },
    ["TabLine"] = { fg = base03, bg = base01 },
    ["TabLineFill"] = { bg = base00 },
    ["TabLineSel"] = { fg = base04, bg = base02 },
    ["Title"] = { fg = base0B },
    ["VertSplit"] = { fg = base0B, bold = maybe.bold },
    ["Visual"] = { bg = base02 },
    ["VisualNOS"] = { link = "Visual" },
    ["WarningMsg"] = { fg = base09 },
    ["Whitespace"] = { link = "NonText" },
    ["WildMenu"] = { link = "IncSearch" },

    -- Code
    ["Boolean"] = { fg = base09 },
    ["Character"] = { fg = base09 },
    ["Comment"] = { fg = base03, italic = maybe.italic },
    ["Conditional"] = { fg = base0C },
    ["Constant"] = { fg = base09 },
    ["Debug"] = { fg = base09 },
    ["Define"] = { fg = base0B },
    ["Delimiter"] = { fg = base04 },
    ["Error"] = { fg = base08 },
    ["Exception"] = { fg = base0C },
    ["Float"] = { fg = base09 },
    ["Function"] = { fg = base0C },
    ["Identifier"] = { fg = base09 },
    ["Include"] = { fg = base0B },
    ["Keyword"] = { fg = base0B },
    ["Label"] = { fg = base0C },
    ["Macro"] = { fg = base0B },
    ["Number"] = { fg = base09 },
    ["Operator"] = { fg = base04 },
    ["PreCondit"] = { fg = base0B },
    ["PreProc"] = { fg = base0B },
    ["Repeat"] = { fg = base0C },
    ["Special"] = { fg = base0C },
    ["SpecialChar"] = { fg = base09 },
    ["SpecialComment"] = { fg = base0B },
    ["Statement"] = { fg = base0C },
    ["StorageClass"] = { fg = base0C },
    ["String"] = { fg = base0A },
    ["Structure"] = { fg = base0C },
    ["Tag"] = { fg = base09 },
    ["Todo"] = { fg = base0B },
    ["Type"] = { fg = base0C },
    ["Typedef"] = { link = "Type" },
    ["Underlined"] = { underline = true },

    -- HTML
    ["htmlArg"] = { fg = base0B },
    ["htmlBold"] = { bold = true },
    ["htmlEndTag"] = { fg = base04 },
    ["htmlH1"] = { link = "@neorg.headings.1.prefix.norg" },
    ["htmlH2"] = { link = "@neorg.headings.2.prefix.norg" },
    ["htmlH3"] = { link = "@neorg.headings.3.prefix.norg" },
    ["htmlH4"] = { link = "@neorg.headings.4.prefix.norg" },
    ["htmlH5"] = { link = "@neorg.headings.5.prefix.norg" },
    ["htmlItalic"] = { italic = maybe.italic },
    ["htmlLink"] = { fg = base0D },
    ["htmlTag"] = { fg = base04 },
    ["htmlTagN"] = { fg = base0B },
    ["htmlTagName"] = { fg = base0C },

    -- Markdown
    ["markdownDelimiter"] = { fg = base04 },
    ["markdownH1"] = { link = "@neorg.headings.1.prefix.norg" },
    ["markdownH1Delimiter"] = { link = "markdownH1" },
    ["markdownH2"] = { link = "@neorg.headings.2.prefix.norg" },
    ["markdownH2Delimiter"] = { link = "markdownH2" },
    ["markdownH3"] = { link = "@neorg.headings.3.prefix.norg" },
    ["markdownH3Delimiter"] = { link = "markdownH3" },
    ["markdownH4"] = { link = "@neorg.headings.4.prefix.norg" },
    ["markdownH4Delimiter"] = { link = "markdownH4" },
    ["markdownH5"] = { link = "@neorg.headings.5.prefix.norg" },
    ["markdownH5Delimiter"] = { link = "markdownH5" },
    ["markdownH6"] = { link = "@neorg.headings.6.prefix.norg" },
    ["markdownH6Delimiter"] = { link = "markdownH6" },
    ["markdownLinkText"] = { fg = base0D, sp = base0D, underline = true },
    ["markdownUrl"] = { link = "markdownLinkText" },
    ["mkdCode"] = { fg = base0C, italic = maybe.italic },
    ["mkdCodeDelimiter"] = { fg = base0A },
    ["mkdCodeEnd"] = { fg = base0C },
    ["mkdCodeStart"] = { fg = base0C },
    ["mkdFootnotes"] = { fg = base0C },
    ["mkdID"] = { fg = base0C, underline = true },
    ["mkdInlineURL"] = { fg = base0D, underline = true },
    ["mkdLink"] = { link = "mkdInlineURL" },
    ["mkdLinkDef"] = { link = "mkdInlineURL" },
    ["mkdListItemLine"] = { fg = base0B },
    ["mkdRule"] = { fg = base04 },
    ["mkdURL"] = { link = "mkdInlineURL" },

    -- Diagnostics
    ["DiagnosticError"] = { fg = base08 },
    ["DiagnosticHint"] = { fg = base0D },
    ["DiagnosticInfo"] = { fg = base0C },
    ["DiagnosticWarn"] = { fg = base09 },
    ["DiagnosticDefaultError"] = { fg = base08 },
    ["DiagnosticDefaultHint"] = { fg = base0D },
    ["DiagnosticDefaultInfo"] = { fg = base0C },
    ["DiagnosticDefaultWarn"] = { fg = base09 },
    ["DiagnosticFloatingError"] = { fg = base08 },
    ["DiagnosticFloatingHint"] = { fg = base0D },
    ["DiagnosticFloatingInfo"] = { fg = base0C },
    ["DiagnosticFloatingWarn"] = { fg = base09 },
    ["DiagnosticSignError"] = { fg = base08 },
    ["DiagnosticSignHint"] = { fg = base0D },
    ["DiagnosticSignInfo"] = { fg = base0C },
    ["DiagnosticSignWarn"] = { fg = base09 },
    ["DiagnosticStatusLineError"] = { fg = base08, bg = base01 },
    ["DiagnosticStatusLineHint"] = { fg = base0D, bg = base01 },
    ["DiagnosticStatusLineInfo"] = { fg = base0C, bg = base01 },
    ["DiagnosticStatusLineWarn"] = { fg = base09, bg = base01 },
    ["DiagnosticUnderlineError"] = { sp = base08, [config.line] = true },
    ["DiagnosticUnderlineHint"] = { sp = base0D, [config.line] = true },
    ["DiagnosticUnderlineInfo"] = { sp = base0C, [config.line] = true },
    ["DiagnosticUnderlineWarn"] = { sp = base09, [config.line] = true },
    ["DiagnosticUnnecessary"] = { fg = base0F },
    ["DiagnosticVirtualTextError"] = { fg = base08 },
    ["DiagnosticVirtualTextHint"] = { fg = base0D },
    ["DiagnosticVirtualTextInfo"] = { fg = base0C },
    ["DiagnosticVirtualTextWarn"] = { fg = base09 },

    -- Healthcheck
    ["healthError"] = { fg = base08 },
    ["healthSuccess"] = { fg = base0C },
    ["healthWarning"] = { fg = base09 },

    -- Treesitter
    ["@boolean"] = { link = "Boolean" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "@character" },
    ["@class"] = { fg = base0C },
    ["@comment"] = { link = "Comment" },
    ["@error"] = { fg = base08 },
    ["@conditional"] = { link = "Conditional" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Constant" },
    ["@constant.macro"] = { link = "@constant" },
    ["@constructor"] = { fg = base0C },
    ["@field"] = { fg = base0C },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Function" },
    ["@function.macro"] = { link = "@function" },
    ["@include"] = { link = "Include" },
    ["@interface"] = { fg = base0C },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.operator"] = { fg = base04 },
    ["@label"] = { link = "Label" },
    ["@macro"] = { link = "Macro" },
    ["@method"] = { fg = base0C },
    ["@number"] = { link = "Number" },
    ["@operator"] = { link = "Operator" },
    ["@parameter"] = { fg = base0D, italic = maybe.italic },
    ["@preproc"] = { link = "PreProc" },
    ["@property"] = { fg = base0C, italic = maybe.italic },
    ["@punctuation"] = { fg = base04 },
    ["@punctuation.bracket"] = { link = "@punctuation" },
    ["@punctuation.delimiter"] = { link = "@punctuation" },
    ["@punctuation.special"] = { link = "@punctuation" },
    ["@regexp"] = { link = "String" },
    ["@repeat"] = { link = "Repeat" },
    ["@storageclass"] = { link = "StorageClass" },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = base0C },
    ["@string.special"] = { link = "@string" },
    ["@symbol"] = { link = "Identifier" },
    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { fg = base0B },
    ["@tag.delimiter"] = { fg = base04 },
    ["@text"] = { fg = base0B },
    ["@text.strong"] = { bold = true },
    ["@text.emphasis"] = { italic = true },
    ["@text.underline"] = { underline = true },
    ["@text.strike"] = { strikethrough = true },
    ["@text.math"] = { link = "Special" },
    ["@text.environment"] = { link = "Macro" },
    ["@text.environment.name"] = { link = "Type" },
    ["@text.reference.vimdoc"] = { link = "Special" },
    ["@text.title"] = { link = "Title" },
    ["@text.uri"] = { fg = base0D },
    ["@text.note"] = { link = "SpecialComment" },
    ["@text.warning"] = { fg = base09 },
    ["@text.danger"] = { fg = base08 },
    ["@todo"] = { link = "Todo" },
    ["@type"] = { link = "Type" },
    ["@variable"] = { fg = base05, italic = maybe.italic },
    ["@variable.builtin"] = { link = "@variable" },
    ["@namespace"] = { link = "@include" },

    -- LSP
    ["LspInlayHint"] = { link = "@comment" },
    ["@lsp"] = {},
    ["@lsp.type.comment"] = {},
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.keyword"] = { link = "@keyword" },
    ["@lsp.type.interface"] = { link = "@interface" },
    ["@lsp.type.namespace"] = { link = "@namespace" },
    ["@lsp.type.parameter"] = { link = "@parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.variable"] = {}, -- use treesitter styles for regular variables
    ["@lsp.typemod.function.defaultLibrary"] = { link = "Function" },
    ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
    ["@lsp.typemod.operator.injected"] = { link = "@operator" },
    ["@lsp.typemod.string.injected"] = { link = "@string" },
    ["@lsp.typemod.variable.injected"] = { link = "@variable" },
    ["LspReferenceText"] = { bg = base0B },
    ["LspReferenceRead"] = { bg = base0B },
    ["LspReferenceWrite"] = { bg = base0B },

    -- hrsh7th/nvim-cmp
    ["CmpItemAbbr"] = { fg = base04 },
    ["CmpItemAbbrDeprecated"] = { fg = base04, strikethrough = true },
    ["CmpItemAbbrMatch"] = { fg = base05, bold = true },
    ["CmpItemAbbrMatchFuzzy"] = { fg = base05, bold = true },
    ["CmpItemKind"] = { fg = base04 },
    ["CmpItemKindClass"] = { fg = base0C },
    ["CmpItemKindFunction"] = { fg = base0A },
    ["CmpItemKindInterface"] = { fg = base0C },
    ["CmpItemKindMethod"] = { fg = base0C },
    ["CmpItemKindSnippet"] = { fg = base0A },
    ["CmpItemKindVariable"] = { fg = base0B },

    -- TimUntersberger/neogit
    ["NeogitSectionHeader"] = { fg = base0D, bold = maybe.bold, underline = true },
    ["NeogitBranch"] = { fg = base0C },
    ["NeogitRemote"] = { fg = base0F },
    ["NeogitObjectID"] = { fg = base0E },
    ["NeogitUnmergedInto"] = { fg = base09 },
    ["NeogitChangeAdded"] = { fg = base0B },
    ["NeogitChangeModified"] = { fg = base0A },
    ["NeogitPopupSwitchKey"] = { fg = base0F },
    ["NeogitDiffAdd"] = { link = "DiffAdd" },
    ["NeogitDiffAddHighlight"] = { link = "DiffAdd" },
    ["NeogitDiffContextHighlight"] = { bg = base01 },
    ["NeogitDiffDelete"] = { link = "DiffRemoved" },
    ["NeogitDiffDeleteHighlight"] = { link = "DiffRemoved" },
    ["NeogitHunkHeader"] = { bg = base01 },
    ["NeogitHunkHeaderHighlight"] = { bg = base01 },

    -- nvim-neorg/neorg
    ["NeorgHeading1Prefix"] = { link = "@neorg.headings.1.prefix.norg" },
    ["NeorgHeading1Title"] = { link = "NeorgHeading1Prefix" },
    ["NeorgHeading2Prefix"] = { link = "@neorg.headings.2.prefix.norg" },
    ["NeorgHeading2Title"] = { link = "NeorgHeading2Prefix" },
    ["NeorgHeading3Prefix"] = { link = "@neorg.headings.3.prefix.norg" },
    ["NeorgHeading3Title"] = { link = "NeorgHeading3Prefix" },
    ["NeorgHeading4Prefix"] = { link = "@neorg.headings.4.prefix.norg" },
    ["NeorgHeading4Title"] = { link = "NeorgHeading4Prefix" },
    ["NeorgHeading5Prefix"] = { link = "@neorg.headings.5.prefix.norg" },
    ["NeorgHeading5Title"] = { link = "NeorgHeading5Prefix" },
    ["NeorgHeading6Prefix"] = { link = "@neorg.headings.6.prefix.norg" },
    ["NeorgHeading6Title"] = { link = "NeorgHeading6Prefix" },
    ["NeorgMarkerTitle"] = { fg = base0B, bold = true },
    ["@neorg.headings.1.prefix.norg"] = { fg = base0D, bold = maybe.bold },
    ["@neorg.headings.1.title.norg"] = { link = "@neorg.headings.1.title.norg" },
    ["@neorg.headings.2.prefix.norg"] = { fg = base0C, bold = maybe.bold },
    ["@neorg.headings.2.title.norg"] = { link = "@neorg.headings.2.title.norg" },
    ["@neorg.headings.3.prefix.norg"] = { fg = base0A, bold = maybe.bold },
    ["@neorg.headings.3.title.norg"] = { link = "@neorg.headings.3.title.norg" },
    ["@neorg.headings.4.prefix.norg"] = { fg = base09, bold = maybe.bold },
    ["@neorg.headings.4.title.norg"] = { link = "@neorg.headings.4.title.norg" },
    ["@neorg.headings.5.prefix.norg"] = { fg = base0B, bold = maybe.bold },
    ["@neorg.headings.5.title.norg"] = { link = "@neorg.headings.5.title.norg" },
    ["@neorg.headings.6.prefix.norg"] = { fg = base0C, bold = maybe.bold },
    ["@neorg.headings.6.title.norg"] = { link = "@neorg.headings.6.title.norg" },
    ["@neorg.markup.verbatim"] = { fg = base03 },
    ["@neorg.anchors.declaration.norg"] = { fg = base0D },

    -- ggandor/leap.nvim
    ["LeapMatch"] = { link = "MatchParen" },
    ["LeapLabelPrimary"] = { link = "Special" },
    ["LeapLabelSecondary"] = { link = "IncSearch" },

    -- nvim-telescope/telescope.nvim
    ["TelescopeBorder"] = { fg = base0B, bg = base01 },
    ["TelescopeMatching"] = { fg = base0A },
    ["TelescopeNormal"] = { fg = base04, bg = base01 },
    ["TelescopePromptNormal"] = { fg = base0B, bg = base01 },
    ["TelescopePromptPrefix"] = { fg = base04 },
    ["TelescopeSelection"] = { fg = base0B, bg = base02 },
    ["TelescopeSelectionCaret"] = { fg = base0A, bg = base02 },
    ["TelescopeTitle"] = { fg = base04 },

    -- rcarriga/nvim-notify
    ["NotifyINFOBorder"] = { fg = base0B },
    ["NotifyINFOTitle"] = { link = "NotifyINFOBorder" },
    ["NotifyINFOIcon"] = { link = "NotifyINFOBorder" },
    ["NotifyWARNBorder"] = { fg = base09 },
    ["NotifyWARNTitle"] = { link = "NotifyWARNBorder" },
    ["NotifyWARNIcon"] = { link = "NotifyWARNBorder" },
    ["NotifyDEBUGBorder"] = { fg = base03 },
    ["NotifyDEBUGTitle"] = { link = "NotifyDEBUGBorder" },
    ["NotifyDEBUGIcon"] = { link = "NotifyDEBUGBorder" },
    ["NotifyTRACEBorder"] = { fg = base0B },
    ["NotifyTRACETitle"] = { link = "NotifyTRACEBorder" },
    ["NotifyTRACEIcon"] = { link = "NotifyTRACEBorder" },
    ["NotifyERRORBorder"] = { fg = base08 },
    ["NotifyERRORTitle"] = { link = "NotifyERRORBorder" },
    ["NotifyERRORIcon"] = { link = "NotifyERRORBorder" },

    -- rcarriga/nvim-dap-ui
    ["DapUIVariable"] = { link = "Normal" },
    ["DapUIValue"] = { link = "Normal" },
    ["DapUIFrameName"] = { link = "Normal" },
    ["DapUIThread"] = { fg = base0A },
    ["DapUIWatchesValue"] = { link = "DapUIThread" },
    ["DapUIBreakpointsInfo"] = { link = "DapUIThread" },
    ["DapUIBreakpointsCurrentLine"] = { fg = base0A, bold = true },
    ["DapUIWatchesEmpty"] = { fg = base08 },
    ["DapUIWatchesError"] = { link = "DapUIWatchesEmpty" },
    ["DapUIBreakpointsDisabledLine"] = { fg = base03 },
    ["DapUISource"] = { fg = base0B },
    ["DapUIBreakpointsPath"] = { fg = base0C },
    ["DapUIScope"] = { link = "DapUIBreakpointsPath" },
    ["DapUILineNumber"] = { link = "DapUIBreakpointsPath" },
    ["DapUIBreakpointsLine"] = { link = "DapUIBreakpointsPath" },
    ["DapUIFloatBorder"] = { link = "DapUIBreakpointsPath" },
    ["DapUIStoppedThread"] = { link = "DapUIBreakpointsPath" },
    ["DapUIDecoration"] = { link = "DapUIBreakpointsPath" },
    ["DapUIModifiedValue"] = { fg = base0C, bold = true },

    -- SmiteshP/nvim-navic
    ["NavicIconsFile"] = { fg = base00 },
    ["NavicIconsModule"] = { fg = base0A },
    ["NavicIconsNamespace"] = { fg = base00 },
    ["NavicIconsPackage"] = { fg = base00 },
    ["NavicIconsClass"] = { fg = base0C },
    ["NavicIconsMethod"] = { fg = base0C },
    ["NavicIconsProperty"] = { fg = base0C },
    ["NavicIconsField"] = { fg = base0C },
    ["NavicIconsConstructor"] = { fg = base0A },
    ["NavicIconsEnum"] = { fg = base0A },
    ["NavicIconsInterface"] = { fg = base0C },
    ["NavicIconsFunction"] = { fg = base0C },
    ["NavicIconsVariable"] = { fg = base0B },
    ["NavicIconsConstant"] = { fg = base0A },
    ["NavicIconsString"] = { fg = base0A },
    ["NavicIconsNumber"] = { fg = base0A },
    ["NavicIconsBoolean"] = { fg = base0A },
    ["NavicIconsArray"] = { fg = base0A },
    ["NavicIconsObject"] = { fg = base0A },
    ["NavicIconsKey"] = { fg = base0B },
    ["NavicIconsKeyword"] = { fg = base0C },
    ["NavicIconsNull"] = { fg = base08 },
    ["NavicIconsEnumMember"] = { fg = base0C },
    ["NavicIconsStruct"] = { fg = base0C },
    ["NavicIconsEvent"] = { fg = base0A },
    ["NavicIconsOperator"] = { fg = base04 },
    ["NavicIconsTypeParameter"] = { fg = base0C },
    ["NavicText"] = { fg = base04 },
    ["NavicSeparator"] = { fg = base04 },

    -- goolord/alpha-nvim
    ["AlphaHeader"] = { fg = base0C },
    ["AlphaButtons"] = { fg = base0C },
    ["AlphaShortcut"] = { fg = base0A },
    ["AlphaFooter"] = { fg = base0A },
  }

  vim.g.terminal_color_0 = base00 -- black
  vim.g.terminal_color_8 = base00 -- bright black
  vim.g.terminal_color_1 = base08 -- red
  vim.g.terminal_color_9 = base08 -- bright red
  vim.g.terminal_color_2 = base0B -- green
  vim.g.terminal_color_10 = base0B -- bright green
  vim.g.terminal_color_3 = base0A -- yellow
  vim.g.terminal_color_11 = base0A -- bright yellow
  vim.g.terminal_color_4 = base0D -- blue
  vim.g.terminal_color_12 = base0D -- bright blue
  vim.g.terminal_color_5 = base0E -- magenta
  vim.g.terminal_color_13 = base0E -- bright magenta
  vim.g.terminal_color_6 = base0C -- cyan
  vim.g.terminal_color_14 = base0C -- bright cyan
  vim.g.terminal_color_7 = base05 -- white
  vim.g.terminal_color_15 = base05 -- bright white

  for group, attrs in pairs(highlights) do
    vim.api.nvim_set_hl(0, group, attrs)
  end
end

return theme
